config/routes.rb
Rails.application.routes.draw do
  root "front_page#index"

  devise_for :users

  get "+all" => "front_page#all"

  resources :channels,
    path: "",
    id: /\+\w+/ do

    post "subscribe" => "channels#subscribe"
    post "unsubscribe" => "channels#unsubscribe"

    resources :posts,
      path: "",
      id: /[\w-]+/,
      except: [:index],
      path_names: { new: "submit" } do

      put "upvote" => "posts#upvote"
      put "downvote" => "posts#downvote"
      put "unvote" => "posts#unvote"

      resources :comments do
        post "reply" => "comments#reply"

        put "upvote" => "comments#upvote"
        put "downvote" => "comments#downvote"
        put "unvote" => "comments#unvote"
      end
    end
  end

  resources :users,
    path: "",
    id: /@\w+/,
    only: [:show]
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  include VoteableHelper
  
  def index
    if current_user
      @posts = current_user.subscribed_posts
    else
      @posts = Post.all
    end

    @posts = @posts
      .includes(:channel, :poster)
      .with_frontpage_score
      .order("frontpage_score DESC")
      .take(15)

    get_upvoted_downvoted(current_user, @posts)

    @channels = Channel
      .order(created_at: :desc)
      .take(5)
  end

  def all
    @posts = Post.all
      .includes(:channel, :poster)
      .order(created_at: :desc)
      .take(15)
  end
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/views/front_page/all.html.erb
<div class="pure-g">
<section class="posts pure-u-1 pure-u-sm-3-5">
  <% @posts.each do |post| %>
    <%= render partial: "posts/post", locals: { post: post, show_channel: true } %>
  <% end %>
</section>

<section class="channel pure-u-1 pure-u-sm-2-5">
  <h2>+all</h2>
  <p><em>It's everything</em></p>
</section>
</div>

app/views/front_page/index.html.erb
<div class="pure-g">
<section class="posts pure-u-1 pure-u-sm-3-5">
  <% @posts.each do |post| %>
    <%= render partial: "posts/post", locals: { post: post, show_channel: true } %>
  <% end %>
</section>

<section class="channel pure-u-1 pure-u-sm-2-5">
  <h2>Front page</h2>

  <h3>See also</h3>
  <ul>
    <li><%= link_to "+all", channel_path(id: "+all") %></li>
  <% @channels.each do |channel| %>
    <li><%= channel_link channel %></li>
  <% end %>
  </ul>
</section>
</div>