config/routes.rb
Rails.application.routes.draw do
  root "front_page#index"

  devise_for :users

  get "+all" => "front_page#all"

  resources :channels,
    path: "",
    id: /\+\w+/ do

    post "subscribe" => "channels#subscribe"
    post "unsubscribe" => "channels#unsubscribe"

    resources :posts,
      path: "",
      id: /[\w-]+/,
      except: [:index],
      path_names: { new: "submit" } do

      put "upvote" => "posts#upvote"
      put "downvote" => "posts#downvote"
      put "unvote" => "posts#unvote"

      resources :comments do
        post "reply" => "comments#reply"

        put "upvote" => "comments#upvote"
        put "downvote" => "comments#downvote"
        put "unvote" => "comments#unvote"
      end
    end
  end

  resources :users,
    path: "",
    id: /@\w+/,
    only: [:show]
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :posts, foreign_key: :channel_name, primary_key: :name
  has_many :channel_subscriptions, foreign_key: :channel_name, primary_key: :name
  has_many :users, through: :channel_subscriptions

  alias_method :subscribers, :users

  RESERVED_NAMES = %w( all random )

  validates :name,
    uniqueness: {
      case_sensitive: false
    },
    length: {
      minimum: 3,
      maximum: 64
    },
    exclusion: {
      in: RESERVED_NAMES,
      case_sensitive: false,
      message: "is a reserved channel name"
    },
    format: {
      with: /\A\w+\z/,
      message: "can only contain letters, numbers and underscores"
    }

  def to_param
    "+#{name}"
  end

  def self.find_by_name(param)
    return nil if param.blank?

    name = param.split("+", 2)[1]

    if name
      channels = Channel.arel_table
      where(channels[:name].lower.eq(name.downcase)).first
    end
  end
end

app/controllers/channel_controller.rb
class ChannelController < ApplicationController

  def show
    @channel = Channel.find_by_name(params[:name])

    render status: 404 unless @channel
  end

  def subscribe
    @channel = Channel.find_by_name(params[:name])

    if current_user.subscribe(@channel)
      flash[:notice] = "Subscribed to #{@channel.name}"
    else
      flash[:alert] = "Already subscribed to #{@channel.name}!"
    end

    redirect_to @channel
  end

  def unsubscribe
    @channel = Channel.find_by_name(params[:name])

    if current_user.unsubscribe(@channel)
      flash[:notice] = "Unubscribed from #{@channel.name}"
    else
      flash[:alert] = "Already unsubscribed from #{@channel.name}!"
    end
    
    redirect_to @channel
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  def show
    @channel = Channel.find_by_name(params[:id])
    
    @posts = @channel.posts
      .includes(:channel, :poster)
      .order(created_at: :desc)
      .take(15)

    render status: 404 unless @channel
  end

  def subscribe
    @channel = Channel.find_by_name(params[:channel_id])

    if current_user.subscribe(@channel)
      flash[:notice] = "Subscribed to #{@channel.name}"
    else
      flash[:alert] = "Already subscribed to #{@channel.name}!"
    end

    redirect_to @channel
  end

  def unsubscribe
    @channel = Channel.find_by_name(params[:channel_id])

    if current_user.unsubscribe(@channel)
      flash[:notice] = "Unubscribed from #{@channel.name}"
    else
      flash[:alert] = "Already unsubscribed from #{@channel.name}!"
    end
    
    redirect_to @channel
  end

end

app/helpers/channel_helper.rb
module ChannelHelper
  def channel_link(channel)
    link_to "+#{channel.name}", channel_path(channel)
  end
end

app/views/channel/_sidebar.html.erb
<section class="channel pure-u-1 pure-u-sm-2-5">
  <h2>#<%= channel.name %></h2>
  <p><em><%= channel.description %></em></p>

  <p>
    <%= link_to "Submit a post ≻", submit_post_path, class: "pure-button pure-button-primary" %>
  </p>

  <p>
    <%= channel.subscribers.count %> subscribers

    <% if current_user %>
      <% if current_user.subscribed?(channel) %>
        <%= link_to "- unsubscribe", channel_unsubscribe_path(channel),
              method: :post, class: "pure-button" %>
      <% else %>
        <%= link_to "+ subscribe", channel_subscribe_path(channel),
              method: :post, class: "pure-button" %>
      <% end %>
    <% else %>
      <p>Log in to subscribe</p>
    <% end %>
  </p>

  <p>
    Moderated by <%= random_username %>, <%= random_username %> and <%= random_username %>.
  </p>

  <h3>Network</h3>

  <ul>
    <li><a href="#">#BlackLivesMatter</a></li>
    <li><a href="#">#Socialism</a></li>
    <li><a href="#">#Communism</a></li>
    <li><a href="#">#Anarchism</a></li>
  </ul>

  <p> <%= link_to "Moderation records", "#" %> </p>

</section>

app/views/channel/show.html.erb
<div class="pure-g">

  <section class="posts pure-u-1 pure-u-sm-3-5">

  <% @channel.posts.each_with_index do |post, i| %>
      <%= render partial: "post/post", locals: { post: post, show_channel: false, i: i } %>
  <% end %>

  </section>

  <%= render partial: "sidebar", locals: { channel: @channel } %>

</div>